version: '2'

services:
  cache:
    container_name: redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - '7379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/data

  database:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: admin999
      POSTGRES_PASSWORD: nHxafTXqAHF4QbVkKheh
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5439:5432"
    restart: unless-stopped

  crawling_data:
    container_name: crawling_data
    restart: on-failure
    build: ./services/crawling_data
    env_file: ./env/.env
    volumes:
      - ./src:/app/src
    ports:
      - "5999:3000"
    depends_on:
      - database
    links:
      - database

  public_api:
    container_name: public_api
    restart: on-failure
    build: ./services/public_api
    env_file: ./env/.env
    volumes:
      - ./src:/app/src
    ports:
      - "6001:3000"
    depends_on:
      - database
      - cache
    links:
      - database

  public_nest:
    container_name: public_nest
    restart: on-failure
    build: ./services/public_nest
    env_file: ./env/.env
    volumes:
      - ./src:/app/src
    ports:
      - "6002:3000"
    depends_on:
      - database
      - cache
    links:
      - database

volumes:
  postgres:
    driver: local
  cache:
    driver: local